### ISSUE TITLE
improvements to nitro vault shares, operator keys

### ISSUE THREAD

**Issue by evq** [brave-intl/bat-go#2105]
```[tasklist]
### Tasks
- [x] write generated shares to files instead of to stdout
- [x] encrypt shares on disk
- [x] pass shares as files instead of flag arg
- [x] encrypt operator keys on disk
- [x] make it easy for operator to get the corresponding public key
```

**Comment by husobee** [comment]
https://github.com/brave-intl/bat-go/pull/2198
