### ISSUE TITLE
Create pull request template / checklist

### ISSUE THREAD

**Issue by evq** [brave-intl/bat-go#364]

**Comment by husobee** [comment]
Here are some things I would want to see in a PR checklist:
```
Before submitting this PR, please make sure:

- [ ] Your code builds clean without any errors or warnings
- [ ] You have added tests for new functionality
- [ ] You have validated query efficiency for new database queries
- [ ] You have documented new functionality in README or in comments
- [ ] You have squashed all intermediate commits
```

**Comment by evq** [comment]
A few others:
- [ ] Have a clear title that explains what the PR does
- [ ] Used intuitive function, variable and other naming
- [ ] Requested security / privacy review if needed
- [ ] Performed a self review of your PR
- [ ] Added a manual test plan if needed (e.g. prod branch release PRs)
- [ ] Used auto closing keywords
